name: Checkmarx

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkmarx Scan
        uses: checkmarx/ast-github-action@main
        id: checkmarx-scan
        with:
          base_uri: https://deu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: accuknox-nfr

  