
name: Container Scan (SANITY)

on:
  workflow_dispatch:

jobs:
  juice-do-sanity:
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - name: Checkout code
        uses: actions/checkout@main  
     
      - name: Run AccuKnox CSPM Scan
        uses: accuknox/container-scan-action@v0.0.1
        with:
          endpoint: ${{ secrets.CSPM_URL }}
          token: ${{ secrets.CSPM_TOKEN }} 
          tenant_id: ${{ secrets.TENANT_ID }}
          repository_name: ${{ github.repository }}
          label: "trivyCICD"
          