
name: Container Scan (SBOM)

on:
  workflow_dispatch:

jobs:
  juice-sbom:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@main
     
      - name: Run AccuKnox CSPM Scan
        uses: accuknox/container-scan-action@latest
        with:
          accuknox_token: ${{ secrets.CSPM_TOKEN }}
          accuknox_label: "dogfooding"
          accuknox_endpoint: ${{ secrets.CSPM_URL }}
          image_name: "pishone/juice-shop"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          soft_fail: false
          keep_results: true
          generate_sbom: true
          project_name: "Juice-Shop"
          