
name: DO Container MultiPlatform

on:
  workflow_dispatch:

jobs:
  juice-do-multiplatform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - windows-latest
          - windows-2022
          - windows-2019
          - macos-latest
          - macos-12
          - macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run container scan
        uses: accuknox/container-scan-action@v0.0.1
        with:
          endpoint: ${{ secrets.DO_ENDPOINT }}
          token: ${{ secrets.DO_TOKEN }} 
          tenant_id: ${{ secrets.DO_TENANT_ID }}
          repository_name: ${{ github.repository }}