
name: DO Container MultiPlatform

on:
  workflow_dispatch:

jobs:
  juice-do-multiplatform:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run container scan
        uses: accuknox/container-scan-action@v0.0.1
        with:
          endpoint: ${{ secrets.DO_ENDPOINT }}
          token: ${{ secrets.DO_TOKEN }} 
          tenant_id: ${{ secrets.DO_TENANT_ID }}
          repository_name: ${{ github.repository }}