name: Opengrep

on:
    push:
    workflow_dispatch:

jobs:
  opengrep-scan:
    name: Opengrep Security Scan
    runs-on: ubuntu-latest
    environment: Stage
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Opengrep Scan
        uses: safeer-accuknox/opengrep-action@1.0.3
        with:
          accuknox_endpoint: ${{ secrets.CSPM_URL }}
          accuknox_tenant: ${{ secrets.TENANT_ID }}
          accuknox_label: 'opengrep'
          accuknox_token: ${{ secrets.CSPM_TOKEN }}
          input_soft_fail: true
          