name: Opengrep not-master

on:
  workflow_dispatch:

jobs:
  accuknox-cicd-not-master:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: not-master

      - name: "Run Accuknox SAST: Opengrep"
        uses: accuknox/sast-scan-opengrep-action@latest
        with:
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: "opengrep1"
          accuknox_ai_analysis: "false"
          soft_fail: "true"

  accuknox-cicd-master:
    needs: accuknox-cicd-not-master
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: master

      - name: "Run Accuknox SAST: Opengrep"
        uses: accuknox/sast-scan-opengrep-action@latest
        with:
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: "opengrep2"
          accuknox_ai_analysis: "false"
          soft_fail: "true"
