name: SQ
on:
  push:
    paths:
      - .github/workflows/sast.yml
  workflow_dispatch:

jobs:
  stage-automation-sast:
    name: Stage Automation
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - name: SAST scan
        uses: accuknox/sast-scan-action@v1.0.1
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          accuknox_endpoint: ${{ secrets.CSPM_URL }}
          accuknox_token: ${{ secrets.CSPM_TOKEN }}
          tenant_id: "5"
          label: "sast"
          sonar_project_key: "dvwa-jenkins"
          input_soft_fail: true
          skip_sonar_scan: true
          upload_artifact: true

  accuknox97-sast:
    name: accuknox97
    runs-on: ubuntu-latest
    environment: accuknox97
    steps:
      - name: SAST scan
        uses: accuknox/sast-scan-action@v1.0.1
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          accuknox_endpoint: ${{ secrets.CSPM_URL }}
          accuknox_token: ${{ secrets.CSPM_TOKEN }}
          tenant_id: "4"
          label: "sonarqube"
          sonar_project_key: "dvwa-jenkins"
          input_soft_fail: true
          skip_sonar_scan: true

  demo21-sast:
    name: demo21
    runs-on: ubuntu-latest
    environment: demo21
    steps:
      - name: SAST scan
        uses: accuknox/sast-scan-action@v1.0.1
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          label: "sonarqube"
          sonar_project_key: "dvwa-jenkins"
          input_soft_fail: true
          skip_sonar_scan: true

  demo-automation-sast:
    name: Demo Automation
    runs-on: ubuntu-latest
    environment: Demo
    steps:
      - name: SAST scan
        uses: accuknox/sast-scan-action@v1.0.1
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          label: "sonarqube"
          sonar_project_key: "dvwa-jenkins"
          input_soft_fail: true
          skip_sonar_scan: true
          