name: trufflehog
on: 
  push:
    paths:
      - .github/workflows/trufflehog-action.yml
  workflow_dispatch:

jobs:
  truffle:
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Accuknox Secret Scan
        uses: Pishone/secret-scan-action@test
        with:
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: "delete"
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          soft_fail: "true"
